name: Continuous deployment

on:
  push:
    branches:
      - production                                        # On push to branch production

jobs:
  build:
    runs-on:                                              # Test environment
      - ubuntu-latest

    steps:
                                                          # Push source code to heroku
      - shell: bash
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_PRODUCTION: ${{ secrets.HEROKU_PRODUCTION }}
        run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_PRODUCTION.git production:master --force
